# Generated by Django 4.0.3 on 2022-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_pd', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('variaciones', models.ImageField(upload_to='', verbose_name='variaciones')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='descripcion')),
                ('id_us', models.IntegerField(verbose_name='usuario')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
            ],
        ),
    ]
