# Generated by Django 4.0.3 on 2022-04-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0002_materia_s_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_cr', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='materia_p',
            fields=[
                ('id_mp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre_mp')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad_mp')),
                ('unidad', models.CharField(max_length=10, verbose_name='unidad_mp')),
                ('costo', models.PositiveIntegerField(verbose_name='costo_mp')),
                ('costo_u', models.IntegerField(verbose_name='costou_mp')),
                ('proveedor', models.CharField(max_length=30, verbose_name='proveedor_mp')),
                ('contacto', models.CharField(max_length=14, verbose_name='contacto_mp')),
                ('tiempo', models.TimeField(verbose_name='tiempo_mp')),
                ('mincant', models.IntegerField(verbose_name='mincant_mp')),
                ('descripcion', models.TextField(max_length=100, verbose_name='descripcion_mp')),
                ('estado', models.BooleanField(verbose_name='estado_mp')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_us', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=20)),
                ('usuario', models.CharField(default=models.IntegerField(primary_key=True, serialize=False), max_length=20)),
                ('contraseña', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.CreateModel(
            name='posicion',
            fields=[
                ('id_ps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre_ps')),
                ('precio', models.IntegerField(verbose_name='precio_ps')),
                ('id_pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.producto', verbose_name='producto')),
                ('id_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.usuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='mezcla',
            fields=[
                ('id_mz', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidaad_mz')),
                ('costo', models.IntegerField(verbose_name='costo_mz')),
                ('id_mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.materia_p', verbose_name='materia primaria')),
                ('id_ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.materia_s', verbose_name='materia secundaria')),
                ('id_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.usuarios', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id_mn', models.AutoField(primary_key=True, serialize=False)),
                ('id_ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.materia_s', verbose_name='materia secundaria')),
                ('id_ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.posicion', verbose_name='posicion')),
            ],
        ),
        migrations.AddField(
            model_name='materia_p',
            name='id_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.usuarios', verbose_name='usuario'),
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id_hs', models.AutoField(primary_key=True, serialize=False)),
                ('id_cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.carrito', verbose_name='carrito')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_ft', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('id_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.usuarios', verbose_name='usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_pd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.producto', verbose_name='producto'),
        ),
        migrations.CreateModel(
            name='armado',
            fields=[
                ('id_ar', models.AutoField(primary_key=True, serialize=False)),
                ('id_cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.carrito', verbose_name='carrito')),
                ('id_mn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.menu', verbose_name='menu')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.usuarios', verbose_name='usuario'),
        ),
    ]
