# Generated by Django 4.0.3 on 2022-04-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0003_carrito_materia_p_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_p',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='contacto',
            field=models.CharField(max_length=14, verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='costo',
            field=models.IntegerField(verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='costo_u',
            field=models.IntegerField(verbose_name='costo unitario'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='mincant',
            field=models.IntegerField(verbose_name='cantidad minima'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='proveedor',
            field=models.CharField(max_length=30, verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='tiempo',
            field=models.TimeField(verbose_name='tiempo de entrega'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='unidad',
            field=models.CharField(max_length=10, verbose_name='unidad'),
        ),
    ]
