# Generated by Django 4.0.3 on 2022-04-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0004_alter_materia_p_cantidad_alter_materia_p_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_p',
            name='tiempo',
            field=models.CharField(max_length=14, verbose_name='tiempo de entrega'),
        ),
    ]
