# Generated by Django 4.0.3 on 2022-04-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0005_alter_materia_p_tiempo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carrito',
            new_name='candycarrito',
        ),
    ]
