# Generated by Django 4.0.3 on 2022-04-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0006_rename_carrito_candycarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default=models.IntegerField(primary_key=True, serialize=False), max_length=20, null=True),
        ),
    ]
