# Generated by Django 4.0.3 on 2022-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0007_alter_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_us',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='lugar',
            field=models.CharField(max_length=20, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ocupacion',
            field=models.CharField(max_length=20, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default='id_us', max_length=20, null=True, verbose_name='Usuario'),
        ),
    ]
