# Generated by Django 4.0.3 on 2022-04-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0008_alter_usuarios_apellido_alter_usuarios_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default='id_us', max_length=20, verbose_name='Usuario'),
        ),
    ]
