# Generated by Django 4.0.3 on 2022-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0010_alter_materia_s_descripcion_alter_materia_s_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candycarrito',
            name='nombre_pd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mezcla',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='mezcla',
            name='costo',
            field=models.IntegerField(verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
