# Generated by Django 4.0.3 on 2022-04-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0011_candycarrito_nombre_pd_alter_mezcla_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armado',
            name='nombre_ms',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
