# Generated by Django 4.0.3 on 2022-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0012_armado_nombre_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='armado',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
