# Generated by Django 4.0.3 on 2022-04-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0013_armado_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='entegados',
            fields=[
                ('id_eg', models.AutoField(primary_key=True, serialize=False)),
                ('mesa', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('id_ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.armado', verbose_name='producto armado')),
            ],
        ),
    ]
