# Generated by Django 4.0.3 on 2022-04-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0014_entegados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entegados',
            new_name='entegado',
        ),
    ]
