# Generated by Django 4.0.3 on 2022-04-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0015_rename_entegados_entegado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entegado',
            name='id_ar',
        ),
        migrations.AddField(
            model_name='entegado',
            name='id_cr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Candyapp.candycarrito', verbose_name='carrito'),
            preserve_default=False,
        ),
    ]
