# Generated by Django 4.0.3 on 2022-04-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0016_remove_entegado_id_ar_entegado_id_cr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='entegado',
        ),
    ]
