# Generated by Django 4.0.3 on 2022-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0018_entegado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entegado',
            new_name='entregado',
        ),
    ]
