# Generated by Django 4.0.3 on 2022-04-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0021_infofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
