# Generated by Django 4.0.3 on 2022-04-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0022_alter_factura_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofactura',
            name='id_eg',
        ),
        migrations.RemoveField(
            model_name='infofactura',
            name='id_ft',
        ),
        migrations.DeleteModel(
            name='historial',
        ),
        migrations.DeleteModel(
            name='infofactura',
        ),
    ]
