# Generated by Django 4.0.3 on 2022-04-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0023_remove_infofactura_id_eg_remove_infofactura_id_ft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='infofactura',
            fields=[
                ('id_if', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('entregado', models.IntegerField(verbose_name='valor entregado')),
                ('cajero', models.CharField(max_length=50, verbose_name='Cajero')),
                ('producto', models.CharField(max_length=50, verbose_name='producto')),
                ('adiciones', models.CharField(max_length=50, verbose_name='adiciones')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('id_ft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candyapp.factura', verbose_name='factura')),
            ],
        ),
    ]
