# Generated by Django 4.0.3 on 2022-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0024_infofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='candycarrito',
            name='precio',
            field=models.IntegerField(default=1, verbose_name='precio'),
            preserve_default=False,
        ),
    ]
