# Generated by Django 4.0.3 on 2022-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0025_candycarrito_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregado',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
