# Generated by Django 4.0.3 on 2022-04-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0027_alter_candycarrito_precio_alter_infofactura_id_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregado',
            name='preciot',
            field=models.IntegerField(null=True),
        ),
    ]
