# Generated by Django 4.0.3 on 2022-04-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0028_entregado_preciot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofactura',
            name='fecha',
            field=models.CharField(max_length=50, verbose_name='Fecha'),
        ),
    ]
