# Generated by Django 4.0.3 on 2022-05-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0031_factura_id_lg_infofactura_lugar_materia_p_id_lg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_us',
        ),
    ]
