# Generated by Django 4.0.3 on 2022-05-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0032_remove_producto_id_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_p',
            name='id_us',
        ),
        migrations.RemoveField(
            model_name='mezcla',
            name='id_us',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='id_us',
        ),
    ]
