# Generated by Django 4.0.3 on 2022-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0033_remove_materia_p_id_us_remove_mezcla_id_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candycarrito',
            name='lugar',
            field=models.CharField(default=1, max_length=20, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregado',
            name='lugar',
            field=models.CharField(default=1, max_length=20, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia_s',
            name='lugar',
            field=models.CharField(default=1, max_length=20, verbose_name='Lugar'),
            preserve_default=False,
        ),
    ]
