# Generated by Django 4.0.3 on 2022-05-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0034_candycarrito_lugar_entregado_lugar_materia_s_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candycarrito',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='entregado',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='materia_s',
            name='lugar',
        ),
        migrations.AddField(
            model_name='candycarrito',
            name='id_lg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Candyapp.lugar', verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregado',
            name='id_lg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Candyapp.lugar', verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia_s',
            name='id_lg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Candyapp.lugar', verbose_name='Lugar'),
            preserve_default=False,
        ),
    ]
