# Generated by Django 4.0.3 on 2022-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0035_remove_candycarrito_lugar_remove_entregado_lugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='variaciones',
        ),
    ]
