# Generated by Django 4.0.3 on 2022-05-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0036_remove_producto_variaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio base'),
            preserve_default=False,
        ),
    ]
