# Generated by Django 4.0.3 on 2022-05-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0038_alter_materia_p_contacto_alter_materia_p_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_us',
        ),
    ]
