# Generated by Django 4.0.3 on 2022-05-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candyapp', '0039_remove_factura_fecha_remove_factura_id_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofactura',
            name='cajero',
        ),
    ]
